version: "3.7"

services:
  postgresql:
    container_name: "postgresql"
    image: postgres:14.5
    hostname: postgresql
    volumes:
      - ./migrations/postgres:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4JLABS_PLUGINS: '["apoc"]'
