"""empty message

Revision ID: ddcf0226eb7e
Revises: 
Create Date: 2022-10-08 02:15:19.313766

"""
from alembic import op
import sqlalchemy as sa
import migrator.models.news
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddcf0226eb7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__jobs'))
    )
    op.create_table('news',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('PROCESSED', 'NEED_PROCESSING', name='newsstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('__ts_vector__', migrator.models.news.TSVector(), sa.Computed("to_tsvector('russian', raw_text)", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__news'))
    )
    op.create_index('ix_video_ts_vector__', 'news', ['__ts_vector__'], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_table('jobs_news',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('job_id', postgresql.UUID(), nullable=False),
    sa.Column('news_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk__jobs_news__job_id__jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk__jobs_news__news_id__news'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__jobs_news'))
    )
    op.create_table('users_jobs',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('users_id', postgresql.UUID(), nullable=False),
    sa.Column('job_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk__users_jobs__job_id__jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk__users_jobs__users_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users_jobs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_jobs')
    op.drop_table('jobs_news')
    op.drop_table('users')
    op.drop_index('ix_video_ts_vector__', table_name='news', postgresql_using='gin')
    op.drop_table('news')
    op.drop_table('jobs')
    # ### end Alembic commands ###
