"""empty message

Revision ID: 3280bed00e2e
Revises: e31cde691b69
Create Date: 2022-10-08 11:12:08.700777

"""
from alembic import op
import sqlalchemy as sa
import models.news
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3280bed00e2e'
down_revision = 'e31cde691b69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'job_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'job_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
