"""empty message

Revision ID: e31cde691b69
Revises: 69121339790f
Create Date: 2022-10-08 06:32:55.785824

"""
from alembic import op
import sqlalchemy as sa
import models.news


# revision identifiers, used by Alembic.
revision = 'e31cde691b69'
down_revision = '69121339790f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'title')
    # ### end Alembic commands ###
