"""empty message

Revision ID: 35a384988a7f
Revises: 3280bed00e2e
Create Date: 2022-10-08 11:37:04.413381

"""
from alembic import op
import sqlalchemy as sa
import models.news


# revision identifiers, used by Alembic.
revision = '35a384988a7f'
down_revision = '3280bed00e2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
